apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-demo
  annotations:
    backstage.io/kubernetes-id: backstage-demo
spec:
  type: website
  lifecycle: production
  owner: user:guest
  

