apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/kubernetes-id: backstage-demo
  name: backstage-demo
spec:
  lifecycle: production
  owner: my-team
  type: service
