apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  POSTGRES_USER: YmFja3N0YWdl
  POSTGRES_PASSWORD: YmFja3N0YWdl

apiVersion: v1
kind: Secret
metadata:
  name: ghe-token
type: Opaque
data:
  GHE_TOKEN: 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
